
project_id = "izykiukrsnmgmtceldet"

[functions.generate-nonce]
verify_jwt = false

[functions.verify-siwe]
verify_jwt = true

[functions.record-mint]
verify_jwt = true

[functions.evaluate-song]
verify_jwt = false
