
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izykiukrsnmgmtceldet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6eWtpdWtyc25tZ210Y2VsZGV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NzA1NzgsImV4cCI6MjA2MDI0NjU3OH0.CKyOY0t0anUkJsol01cbxdi9JQcjeawskyYYtNn05Wk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
